name: Linkspector
on: [push]
jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List all files (Debugging)
        run: |
          echo "Listing all files to be scanned:"
          ls -R .
      - name: Run linkspector with reviewdog flags
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check  # You can still specify the reporter here
          fail_on_error: true
          config_file: ".github/workflows/.linkspector.yml"
