name: Linkspector
on: [push]
jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List all files (Debugging)
        run: |
          echo "Listing all files to be scanned:"
          ls -R .
      - name: Run linkspector with detailed logging
        run: |
          linkspector --config .github/workflows/.linkspector.yml | tee output.log
          cat output.log  # Display the output from linkspector
